version: '3'

services:
  backend:
    build:
      context: ./be  # 백엔드 Dockerfile이 위치한 디렉토리
      dockerfile: Dockerfile
    command: gunicorn myproject.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./be:/app
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./fe/my-app  # 프론트엔드 Dockerfile이 위치한 디렉토리
      dockerfile: Dockerfile
    command: npm start
    volumes:
      - ./fe/my-app:/app
    ports:
      - "3000:3000"
