version: '3'

services:
  backend:
    build:
      context: ./be  # 백엔드 Dockerfile이 위치한 디렉토리
      dockerfile: Dockerfile
    command: gunicorn --bind 0.0.0.0:8000 config.wsgi:application
    volumes:
      - ./be:/app
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./fe/my-app  # 프론트엔드 Dockerfile이 위치한 디렉토리
    ports:
      - "80:80"  # Nginx는 80번 포트에서 서빙
