# Generated by Django 5.0.7 on 2024-08-23 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test3', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
