# Generated by Django 5.0.7 on 2024-08-14 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='full_name',
            field=models.CharField(default=1, editable=False, max_length=255),
            preserve_default=False,
        ),
    ]
