# .github/workflows/deploy.yml
name: Deploy Django to AWS EC2 with Git

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH Keys
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}

    - name: Sync and Deploy
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} "
        if [ ! -d \"/home/ubuntu/myproject\" ]; then
          git clone https://github.com/yangchanghun/white.git /home/ubuntu/myproject
        else
          cd /home/ubuntu/myproject
          git pull
        fi
        cd /home/ubuntu/myproject
        docker-compose down
        docker-compose up -d --build
        "
