#hi
name: Deploy Django and Frontend to AWS EC2 with Git

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH
      run: |
        eval $(ssh-agent -s)        echo "${{ secrets.SSH_KEY }}" | tr -d '\r' | ssh-add -

    - name: Sync and Deploy
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} "
        if [ ! -d \"/home/ubuntu/myproject\" ]; then
          git clone https://github.com/yangchanghun/white.git /home/ubuntu/myproject
        else
          cd /home/ubuntu/myproject
          git pull
        fi
        cd /home/ubuntu/myproject
        docker-compose down
        docker-compose up -d --build
        "
