name: Deploy Django to AWS EC2 with Git

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH Keys
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}

    - name: Sync and Deploy
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} '
        if [ ! -d "/home/ubuntu/yourproject" ]; then
          mkdir -p /home/ubuntu/yourproject
          git clone https://github.com/yangchanghun/white /home/ubuntu/yourproject
        else
          cd /home/ubuntu/yourproject
          git pull
        fi
        sudo /usr/local/bin/docker-compose build
        sudo /usr/local/bin/docker-compose down
        sudo /usr/local/bin/docker-compose up -d
        '
